name: Daily Ayeh Bot

on:
  schedule:
    - cron: "30 4 * * *"

  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python main.py --once

      - name: Commit updated state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add state.json

          git diff --cached --quiet && exit 0

          git commit -m "Update state"

          git pull --rebase origin main

          git push origin main